"""Tables emitted as LaTeX source, for the documents to include as they are.

Three tables travel from this pipeline into the deliverables as tables rather
than as pictures: the casualty matrix of each dataset, and the correlation among
the variables that enter the models. All three are shaded, all three change on
every run, and all three used to be transcribed by hand into the document.

Transcription is what this module exists to remove. A figure typed from a CSV
into a `.tex` can be typed wrongly, and once it is there nothing records which
run produced it, so a number in a slide cannot be checked against the data six
weeks later. What comes out of here carries the run in a comment at the top and
is included whole.

The output is deliberately incomplete: a `tblr` and nothing around it. Captions,
column widths and placement belong to the document, which knows how much room it
has; the pipeline knows the numbers. Each file is `\\input` inside whatever
`table` environment the document sets up.

What the document has to provide is the template's own preamble: `tabularray`,
`siunitx`, `fontawesome5`, and the colours ColorEnfasis, ColorAlrt and ColorNav.
Every one of those is already there in the presentation and in the report.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

import numpy as np
import pandas as pd

try:  # regular package import
    from src import config
    from src.provenance import RunLog
except ImportError:  # executed as a plain script from inside src/
    import config  # type: ignore[no-redef]
    from provenance import RunLog  # type: ignore[no-redef]


# ---------------------------------------------------------------------------
# Shading
# ---------------------------------------------------------------------------


def shade(intensity: float) -> int:
    """Turn a 0-to-1 intensity into a percentage of the accent colour.

    Clamped at both ends and capped by the declared ceiling, so no arithmetic
    upstream can produce a cell darker than the ceiling allows. The ceiling is
    about whether the text on the cell can be read, which is not a property of
    the data and must not be left to it.
    """
    bounded = min(max(intensity, 0.0), 1.0)
    return int(round(bounded * config.LATEX_SHADE_CEILING))


def _cell(text: str, *, percent: int, color: str, bold: bool = False) -> str:
    """One table cell, shaded only when the shading would be visible.

    A cell at zero percent gets no `SetCell` at all rather than one asking for
    zero percent of a colour. The two render identically, and the shorter form
    keeps the emitted source readable, which matters because a human does open
    these files when a table looks wrong.
    """
    options = []
    if percent > 0:
        options.append(f"bg={color}!{percent}")
    if bold:
        options.append(r"font=\bfseries")
    if not options:
        return text
    return f"\\SetCell{{{', '.join(options)}}} {text}"


def _header(run_dir: Path, description: str) -> str:
    """The provenance line every emitted table carries.

    A LaTeX comment, so it never reaches the compiled page, and the first thing
    in the file, so anyone opening it sees which run the numbers came from before
    reading a single one of them.
    """
    return (
        f"% {description}\n"
        f"% generated by the pipeline from {run_dir.name} "
        f"on {dt.date.today().isoformat()}; do not edit by hand, it is overwritten\n"
    )


# ---------------------------------------------------------------------------
# The casualty matrix
# ---------------------------------------------------------------------------


def matrix_table(counts: pd.DataFrame) -> str:
    """One casualty matrix as a `tblr`, actor rows against counterpart columns.

    Shaded on its own maximum rather than on a scale shared with the other
    matrix. Within one table that is what lets its internal structure be read;
    across two tables it means the shading cannot be compared, which is why the
    caption in the document has to say so.

    The ramp is a square root, because the counts span four orders of magnitude
    and a proportional ramp would leave everything but the largest handful of
    cells looking like white.
    """
    values = counts.to_numpy(dtype=float)
    largest = float(values.max())

    icons = [config.LATEX_ACTOR_ICONS[name] for name in counts.columns]
    lines = ["    & " + " & ".join(icons) + r" \\"]

    for actor in counts.index:
        cells = []
        for counterpart in counts.columns:
            value = float(counts.loc[actor, counterpart])
            intensity = (value / largest) ** config.LATEX_COUNT_SHADE_EXPONENT if largest > 0 else 0.0
            cells.append(
                _cell(
                    f"\\num{{{int(value)}}}",
                    percent=shade(intensity),
                    color=config.LATEX_POSITIVE_COLOR,
                )
            )
        lines.append(f"    {config.LATEX_ACTOR_ICONS[actor]} & " + " & ".join(cells) + r" \\")

    column_spec = "Q[r]" + "Q[c]" * len(counts.columns)
    return "\n".join(
        [
            "\\begin{tblr}{",
            f"    colspec = {{{column_spec}}},",
            "    cells = {font=\\tiny},",
            f"    row{{1}} = {{font=\\scriptsize, fg={config.LATEX_LABEL_COLOR}}},",
            f"    column{{1}} = {{font=\\scriptsize, fg={config.LATEX_LABEL_COLOR}}},",
            "    rowsep = 0.7pt,",
            "    colsep = 4pt,",
            "    hline{2} = {-}{0.4pt, black!40},",
            "    vline{2} = {-}{0.4pt, black!40},",
            "}",
            *lines,
            "\\end{tblr}",
        ]
    )


def matrix_counts(long_table: pd.DataFrame, count_names: tuple[str, ...]) -> pd.DataFrame:
    """One of the deliverable matrices, adding its counts together.

    Persons is injured plus killed. That sum happens here and nowhere else: the
    pipeline carries the two apart from the first step on purpose, because deaths
    are about three per cent of the records and merging them earlier would bury
    them. A document that wants the two together says so at the point of
    printing.
    """
    columns = [config.MATRIX_COUNTS[name] for name in count_names]
    table = long_table.pivot_table(
        index=config.PARTY_TYPE_COL,
        columns=config.COUNTERPART_TYPE_COL,
        values=columns,
        aggfunc="sum",
        fill_value=0,
    )
    # pivot_table over several value columns returns them on an outer level;
    # summing across it is what turns injured and killed into persons.
    summed = table.T.groupby(level=1).sum().T if len(columns) > 1 else table.droplevel(0, axis=1)
    return summed.reindex(
        index=list(config.MATRIX_ROW_ORDER),
        columns=list(config.MATRIX_COLUMN_ORDER),
        fill_value=0,
    ).astype(int)


def export_matrices(long_table: pd.DataFrame, dataset: str, log: RunLog) -> dict[str, Path]:
    """Write every deliverable matrix of one dataset as LaTeX source."""
    data_dir = log.run_dir / config.DATA_SUBDIR
    data_dir.mkdir(parents=True, exist_ok=True)
    suffix = config.LATEX_DATASET_SUFFIXES[dataset]

    paths: dict[str, Path] = {}
    for table_name, (count_names, description) in config.LATEX_MATRIX_TABLES.items():
        counts = matrix_counts(long_table, count_names)
        name = f"{config.PRESENTATION_PREFIX}__matrix_{table_name}__{suffix}{config.LATEX_TABLE_SUFFIX}"
        path = data_dir / name
        path.write_text(
            _header(log.run_dir, f"{description} {dataset} dataset, every year.")
            + matrix_table(counts)
            + "\n",
            encoding="utf-8",
        )
        paths[table_name] = path

    log.info(
        "%s: wrote %d matrices as LaTeX source (%s)",
        dataset,
        len(paths),
        ", ".join(path.name for path in paths.values()),
    )
    return paths


# ---------------------------------------------------------------------------
# The correlation of the model set
# ---------------------------------------------------------------------------


def correlation_table(correlation: pd.DataFrame, labels: list[str]) -> str:
    """The correlation as a numbered lower triangle.

    Only the lower half is printed. The matrix is symmetric, so the upper half
    would repeat every figure, and the diagonal is 1 by construction and says
    nothing. The dash on the diagonal is what ties a column number to a row name,
    which is what lets the columns be labelled with numbers alone instead of
    carrying the eleven-character names twice.

    Two visual channels, answering two questions that must not be conflated. The
    colour is the sign and the magnitude, on a ramp with a fixed ceiling. The
    bold is the statistical claim: this pair is at or above the threshold the
    surrounding text quotes.
    """
    size = len(labels)
    lines = ["    & " + " & ".join(str(i + 1) for i in range(size)) + r" \\"]

    for row in range(size):
        cells = []
        for column in range(size):
            if column > row:
                cells.append("")  # the upper triangle is left empty, not blanked out
                continue
            if column == row:
                cells.append(f"\\SetCell{{fg={config.LATEX_DIAGONAL_COLOR}}} --")
                continue

            value = float(correlation.iloc[row, column])
            high = abs(value) >= config.CORRELATION_HIGH_THRESHOLD
            # Rounding a small negative correlation to two places yields "-0.00",
            # which reads as a signed quantity that is not zero. Add zero to it and
            # the sign goes: the cell says 0.00, which is what two decimal places
            # of that number are able to claim.
            rounded = round(value, config.LATEX_CORRELATION_DECIMALS) + 0.0
            printed = f"{rounded:.{config.LATEX_CORRELATION_DECIMALS}f}"
            # detect-weight only where the cell is bold: siunitx has to be told to
            # follow the surrounding weight, or the figure sets itself upright in
            # the middle of a bold cell.
            number = f"\\num[detect-weight]{{{printed}}}" if high else f"\\num{{{printed}}}"
            cells.append(
                _cell(
                    number,
                    percent=shade(abs(value)),
                    color=config.LATEX_POSITIVE_COLOR if value >= 0 else config.LATEX_NEGATIVE_COLOR,
                    bold=high,
                )
            )
        lines.append(f"    {row + 1}~{labels[row]} & " + " & ".join(cells) + r" \\")

    column_spec = "Q[l]" + "Q[c]" * size
    return "\n".join(
        [
            "\\begin{tblr}{",
            f"    colspec = {{{column_spec}}},",
            f"    row{{1}} = {{fg={config.LATEX_LABEL_COLOR}}},",
            f"    column{{1}} = {{fg={config.LATEX_LABEL_COLOR}}},",
            "    rowsep = 2.0pt,",
            "    colsep = 0.8pt,",
            "    hline{2} = {-}{0.4pt, black!40},",
            "    vline{2} = {-}{0.4pt, black!40},",
            "}",
            *lines,
            "\\end{tblr}",
        ]
    )


def export_correlation(correlation: pd.DataFrame, log: RunLog) -> Path:
    """Write the correlation of the model set as LaTeX source, labelled in Spanish."""
    data_dir = log.run_dir / config.DATA_SUBDIR
    data_dir.mkdir(parents=True, exist_ok=True)

    labels = [config.STATIC_PREDICTORS_BY_NAME[name].label_es for name in correlation.columns]
    path = data_dir / f"{config.PRESENTATION_PREFIX}__model_correlation{config.LATEX_TABLE_SUFFIX}"
    path.write_text(
        _header(
            log.run_dir,
            f"Pearson correlation among the {len(labels)} variables that enter the models.",
        )
        + correlation_table(correlation, labels)
        + "\n",
        encoding="utf-8",
    )
    log.info("wrote the model correlation as LaTeX source (%s)", path.name)
    return path


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------


def verify_matrix_table(long_table: pd.DataFrame, dataset: str, log: RunLog) -> bool:
    """Do the emitted matrices still add up to what the long table holds?

    Cheap, and it catches the one failure that would otherwise be invisible: a
    reshape that drops a pair or double counts one still produces a table that
    looks perfectly reasonable on a slide.
    """
    passed = True
    for table_name, (count_names, _) in config.LATEX_MATRIX_TABLES.items():
        emitted = int(matrix_counts(long_table, count_names).to_numpy().sum())
        expected = int(sum(long_table[config.MATRIX_COUNTS[name]].sum() for name in count_names))
        if emitted != expected:
            log.warn(
                "%s: the %s table totals %d, but the long table holds %d",
                dataset,
                table_name,
                emitted,
                expected,
            )
            passed = False
        else:
            log.info("%s: the %s table totals %s, matching the long table", dataset, table_name, f"{emitted:,}")
    return passed


def verify_correlation_table(correlation: pd.DataFrame, log: RunLog) -> bool:
    """Is the correlation the model set's, and is it a correlation at all?"""
    passed = True
    expected = list(config.MODEL_PREDICTOR_NAMES)
    if list(correlation.columns) != expected:
        log.warn(
            "the correlation covers %s, but the model set is %s",
            ", ".join(correlation.columns),
            ", ".join(expected),
        )
        passed = False

    values = correlation.to_numpy(dtype=float)
    if not np.allclose(values, values.T, equal_nan=True):
        log.warn("the correlation matrix is not symmetric, and a correlation matrix always is")
        passed = False
    if not np.allclose(np.diag(values), 1.0):
        log.warn("the diagonal of the correlation matrix is not 1")
        passed = False

    off_diagonal = values[~np.eye(len(values), dtype=bool)]
    if np.nanmax(np.abs(off_diagonal)) > 1.0:
        log.warn("the correlation matrix holds a value outside [-1, 1]")
        passed = False

    return passed
